module.exports = {
  'oneSeed' : 'MZSPOX9P9FJAJVFSFFGUQBLTZVB9HFFNEBVGNFDPPFHNGFLKLTSORVYULFJSAOPRAOGHCSVOAGUQT9QKF',
  'twoSeed' : 'JDDEYUOYLXPIYZCNINADWEEIBXNMYGMXBBYUXOJTOAZEQMI9LLRHKFOXFXPWTIAPVG9QTAWQDSMOPAEHG',
  'oneSettlement' : 'RETBXKYEJCURBZ9UBGYP9DGE9THWZL9WAZMAO9LWAKVEYGPREIOPMNOKPBA9I9ZDGREAOUQJPOW',
  'twoSettlement' : 'EUJWHMGENOQEWKJMHQFXUPHTHRYMGCTDUSOSOKVRWIPMMTKULTZTNNKZOBOJWJFEGFGBEOGMNHP',
  'SECURITY' : 2,
  'SIGNERS_COUNT' : 2,
  'TREE_DEPTH' : 4,
  'CHANNEL_BALANCE' : 2000,
  'DEPOSITS' : [1000, 1000],
}